# Creates all 1 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# HPiLO — Currently unused.
# ---------------------------------------------------------------------------
New-StoreType "HPiLO" @'
{
  "Name": "HP iLO Cert Store",
  "ShortName": "HPiLO",
  "Capability": "HPiLO",
  "LocalStore": false,
  "StorePathDescription": "This should contain the full URI pointing to the HPiLO instance, using IP (e.g. `https://10.1.1.1/`) or domain name (e.g. `https://hpilo.test.local/`). The orchestrator will connect to the iLO instance using the iLO API.",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "InventoryAll",
      "DisplayName": "InventoryAll",
      "Type": "Bool",
      "DependsOn": null,
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "IgnoreValidation",
      "DisplayName": "IgnoreValidation",
      "Type": "Bool",
      "DefaultValue": "false",
      "DependsOn": null,
      "Required": true
    },
    {
      "Name": "HTTPSCertWaitTime",
      "DisplayName": "HTTPS Cert Wait Time",
      "Type": "String",
      "DefaultValue": "60",
      "DependsOn": null,
      "Required": true
    }
  ],
  "EntryParameters": [
    {
      "Name": "IncludeIP",
      "DisplayName": "IncludeIP",
      "Type": "Bool",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DependsOn": "",
      "DefaultValue": "false",
      "Description": "Enables the addition of the device IP as a SAN to the CSR during reenrollment. Used particularly during HTTPSCert reenrollment, where it can be set as desired, and should be set to false during all other operations."
    }
  ],
  "PasswordOptions": {
    "EntrySupported": true,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@


Write-Host "Completed."
